name: Internal Release

# Controls when the workflow will run
on:
  # Triggers the workflow on push of version tag
  push:
    branches:
      - 'main'
    tags:
      - '*.*.*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  internal_release:
    # The type of runner that the job will run on
    # Runs on macos-latest because Android Emulator won't HAXM hardware acceleration on Ubuntu
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout GIT
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 #Fetch all history for all branches and tags

      - name: Setup Java SDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      #----------------------------------------------------

      #Security
      - name: Validate Gradle Wrapper checksum
        uses: gradle/wrapper-validation-action@v1

      - name: Make Gradle Wrapper (gradlew) executable
        run: chmod +x gradlew
      #----------------------------------------------------

      #Optimization
      - name: Enable Gradle Wrapper caching (optmization)
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      #---------------------------------------------------

      #Verify (Lint + Maven local publish test)
      - name: Verify stability
        run: |
          ./gradlew lintRelease
          ./gradlew publishToMavenLocal
      #-----------------------------------------------------------------

      #Create GitHub release
      # Bullrich/generate-release-changelog@master doesn't run on macos-latest
      - name: Prepare changelog for GitHub Release
        uses: Bullrich/generate-release-changelog@master
        id: Changelog
        env:
          REPO: ${{ github.repository }}

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ${{ steps.Changelog.outputs.changelog }}
          draft: false
          prerelease: false
